[package]
distribution = "2201.13.1"
org = "avi0ra"
name = "huggingface"
version = "2.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = []
icon = "icon.png"
repository = "https://github.com/HasithaErandika/module-ballerinax-huggingface"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
